FROM python:3.9
EXPOSE 8000
WORKDIR /app
COPY ./backend /app
#COPY ./ecommerce_docker_deployment/backend/requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install django-environ
RUN python manage.py makemigrations account
RUN python manage.py makemigrations payments
RUN python manage.py makemigrations product
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]